<?php

/**
 * @file
 * Main file for openy_gc_auth_yusa module.
 */

/**
 * Implements hook_mail().
 */
function openy_gc_auth_yusa_mail($key, &$message, $params) {
  switch ($key) {
    case 'email_verification':
      $site_config = \Drupal::config('system.site');
      $message['from'] = $site_config->get('mail');
      $message['subject'] = t('@site_name: Virtual Y email verification', [
        '@site_name' => $site_config->get('name'),
      ]);
      $message['body'][] = $params['message'];
      break;
  }
}
