<?php

/**
 * @file
 * Contains openy_gc_personal_training.module.
 */

/**
 * Implements hook_preprocess_html().
 *
 * Attach openy_gc_personal_training/simple_peer library.
 */
function openy_gc_personal_training_preprocess_html(&$variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if ($node->hasField('field_content')) {
      foreach ($node->field_content as $field_item) {
        if ($field_item->entity->bundle() === 'gated_content') {
          $variables['#attached']['library'][] = 'openy_gc_personal_training/simple_peer';
        }
      }
    }

    if ($node->hasField('field_bottom_content')) {
      foreach ($node->field_bottom_content as $field_item) {
        if ($field_item->entity->bundle() === 'gated_content') {
          $variables['#attached']['library'][] = 'openy_gc_personal_training/simple_peer';
        }
      }
    }
  }
}

/**
 * Implements hook_virtual_y_app_settings_alter().
 */
function openy_gc_personal_training_virtual_y_app_settings_alter(&$config) {

  $config['personal_training_enabled'] = TRUE;
  $moduleConfig = \Drupal::config('openy_gc_personal_training.settings');
  $config['peerjsDomain'] = $moduleConfig->get('peerjs_domain');
  $config['peerjsPort'] = $moduleConfig->get('peerjs_port');
  $config['peerjsUri'] = $moduleConfig->get('peerjs_uri');

}
