<?php

/**
 * @file
 * Contains openy_gc_livechat.module.
 */

/**
 * Implements hook_theme().
 */
function openy_gc_livechat_theme() {
  return [
    'livechat_block' => [
      'variables' => [
        'form' => '',
      ],
      'template' => 'block--livechat-block',
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function openy_gc_livechat_cron() {
  // Delete chat messages older than 30 days.
  \Drupal::database()->delete('openy_gc_livechat__chat_history')
    ->condition('created', time() - 2592000, '<=')
    ->execute();
}

/**
 * Implements hook_page_attachments().
 */
function openy_gc_livechat_page_attachments(array &$attachments) {
  $attachments['#attached']['drupalSettings']['isLiveChatModuleEnabled'] = TRUE;
}
