<?php

/**
 * @file
 * Contains openy_gc_log.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_paragraph().
 */
function openy_gc_log_preprocess_paragraph(array &$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  $paragraphs_list = ['gated_content', 'gated_content_login'];
  if (!in_array($paragraph->bundle(), $paragraphs_list)) {
    return;
  }

  $variables['#attached']['library'][] = 'openy_gc_log/logger';
}

/**
 * Implements hook_preprocess_views_view().
 */
function openy_gc_log_preprocess_views_view(array &$variables) {
  if ($variables['view']->storage->id() !== 'virtual_y_logs') {
    return;
  }

  $variables['#attached']['library'][] = 'openy_gc_log/datepicker';
}

/**
 * Implements hook_cron().
 */
function openy_gc_log_cron() {
  \Drupal::service("openy_gc_log.log_archiver")->archive();
}

/**
 * Implements hook_help().
 */
function openy_gc_log_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the openy_gc_log module.
    case 'help.page.openy_gc_log':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Virtual Y Log') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_file_download().
 */
function openy_gc_log_file_download($uri) {
  $user = \Drupal::currentUser();

  if (!$user->hasPermission('view log entity entities')) {
    return NULL;
  }

  if (strpos($uri, 'vy_logs/' === FALSE)) {
    return NULL;
  }

  return [
    'Content-Type' => \Drupal::service('file.mime_type.guesser')->guess($uri),
    'Content-Disposition' => 'inline',
  ];
}
